version: '2'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=smac
      - INFLUXDB_ADMIN_USER=smac
      - INFLUXDB_ADMIN_PASSWORD=smac
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=smac
      - GF_SECURITY_ADMIN_PASSWORD=smac
volumes:
  influxdb-volume:
  grafana-volume:
